// Code generated by sqlc. DO NOT EDIT.

package mysql

import (
	"database/sql"
	"time"
)

type Secret struct {
	ID         string
	Content    string
	Passphrase sql.NullString
	ExpiresAt  time.Time
}
